Repository auth0/Lock.swift, pull requests merged in 2019-07, with the labels that each got.

#555 Fix secondary button color after switching tabs
  Lock/DatabaseOnlyView.swift
Labels: CH: Fixed

#559 Fixed use default .fullScreen modalPresentationStyle
  Lock/LockViewController.swift
Labels: CH: Fixed, tiny

#561 Update Gems
  Gemfile.lock
Labels: tiny

#560 Expanded username validation characters
  Lock/Validators.swift
Labels: CH: Added, small

#562 Release 2.11.0
  App/Info.plist
  CHANGELOG.md
  Lock/Info.plist
  LockTests/Info.plist
  LockUITests/Info.plist
  README.md
Labels: tiny
