Repository auth0/Lock.swift, pull requests merged in 2020-03, with the labels that each got.

#600 Update AuthButton style to match Lock.js [SDK-1376]
  App/ViewController.swift
  Lock/AuthButton.swift
  Lock/AuthStyle.swift
  Lock/Base.lproj/Lock.strings
  LockTests/AuthCollectionViewSpec.swift
  LockTests/Models/AuthStyleSpec.swift
Labels: CH: Changed, review:small

#601 Release 2.16.0 [SDK-1402]
  App/Info.plist
  CHANGELOG.md
  Lock/Info.plist
  LockTests/Info.plist
  LockUITests/Info.plist
  README.md
Labels: review:small

#603 Fixes crash in banner presentation
  Lock/AuthPresenter.swift
Labels: F1: inspection required

#604 Release 2.16.1
  App/Info.plist
  CHANGELOG.md
  Lock/Info.plist
  LockTests/Info.plist
  LockUITests/Info.plist
Labels: review:small
