Repository auth0/Lock.swift, pull requests merged in 2020-01, with the labels that each got.

#587 Added hidden CustomTextField support
  Lock/CustomTextField.swift
  Lock/DatabaseOnlyView.swift
  Lock/DatabasePresenter.swift
  Lock/InputField.swift
  Lock/SignUpView.swift
  LockTests/InputFieldSpec.swift
  LockTests/Presenters/DatabasePresenterSpec.swift
  README.md
Labels: CH: Added

#590 Allow rule text color customization [SDK-1243]
  App/ViewController.swift
  Lock/DatabaseOnlyView.swift
  Lock/PolicyView.swift
  Lock/Style.swift
  LockTests/PolicyViewSpec.swift
Labels: CH: Added, enhancement, review:small

#591 Replaced old passwordless authentication method [SDK-1186]
  Cartfile
  Cartfile.resolved
  Lock.podspec
  Lock/AuthStyle.swift
  Lock/OptionBuildable.swift
  Lock/PasswordlessInteractor.swift
  Lock/PasswordlessRouter.swift
  LockTests/Interactors/PasswordlessInteractorSpec.swift
  LockTests/Models/AuthStyleSpec.swift
  LockTests/OptionsSpec.swift
  LockTests/Utils/NetworkStub.swift
Labels: CH: Changed, P1: Urgent, review:small

#592 Release 2.14.0
  App/Info.plist
  CHANGELOG.md
  Lock/Info.plist
  LockTests/Info.plist
  LockUITests/Info.plist
  README.md
Labels: review:tiny

#593 Update README and CHANGELOG for Passwordless
  CHANGELOG.md
  README.md
Labels: documentation, review:tiny

#594 Made email/domain match case-insensitive
  Lock/Colors.swift
  Lock/DatabasePresenter.swift
  Lock/EnterpriseDomainInteractor.swift
  Lock/HeaderView.swift
  Lock/MessageView.swift
  Lock/OptionBuildable.swift
  Lock/PolicyView.swift
  Lock/SingleInputView.swift
  Lock/Style.swift
  LockTests/Interactors/EnterpriseDomainInteractorSpec.swift
Labels: CH: Fixed, review:small

#595 Internationalised hardcoded strings
  Lock/Base.lproj/Lock.strings
  Lock/DatabasePresenter.swift
  Lock/Validators.swift
Labels: CH: Fixed, tiny
