Repository auth0/Lock.swift, pull requests merged in 2020-04, with the labels that each got.

#608 Fixed signup form state bug [SDK-1490]
  Lock/DatabasePresenter.swift
Labels: CH: Fixed, tiny

#610 Changed the background color to black
  Lock/AuthStyle.swift
Labels: CH: Fixed, tiny

#606 [Snyk] Fix for 3 vulnerabilities
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: CH: Security, review:small

#611 Fixed auth button highlighted color issue
  Lock/AuthButton.swift
  Lock/AuthStyle.swift
Labels: CH: Fixed, review:small

#612 Release 2.17.0
  App/Info.plist
  CHANGELOG.md
  Lock/Info.plist
  LockTests/Info.plist
  LockUITests/Info.plist
  README.md
Labels: review:small
