Repository auth0/Lock.swift, pull requests merged in 2021-02, with the labels that each got.

#655 Fixed enterprise form validation [SDK-2327]
  Cartfile.resolved
  Lock/CredentialView.swift
  LockTests/Presenters/DatabasePresenterSpec.swift
Labels: CH: Fixed, review:tiny

#649 Support OOB MFA challenges
  Cartfile
  Cartfile.resolved
  Lock.podspec
  Lock/MultifactorInteractor.swift
  LockTests/Interactors/MultifactorInteractorSpec.swift
  LockTests/Utils/Mocks.swift
  LockTests/Utils/NetworkStub.swift
  Package.swift
Labels: needs investigation

#656 Enabled Xcode code coverage
  .circleci/config.yml
  Lock.xcodeproj/xcshareddata/xcschemes/Lock.xcscheme
Labels: review:tiny

#660 Fixed retain cycles on DatabasePresenter [SDK-2360]
  Lock/DatabasePresenter.swift
Labels: CH: Fixed, review:tiny
